trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, World!
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'tar'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
  displayName: 'Run a one-line script'

- script: |
    echo To add more tasks
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
